parameters:
    liip_theme.file_locator.class: SmartCore\Bundle\CMSBundle\Twig\Locator\ModuleThemeLocator
    liip_theme.templating_locator.class: SmartCore\Bundle\CMSBundle\Twig\Locator\TemplateLocator
    liip_theme.filesystem_loader.class: SmartCore\Bundle\CMSBundle\Twig\Loader\FilesystemLoader
    admin_path: admin
    user_path: user

cms:
    # database (db), filesystem (fs)
    #storage: db
        # настройки для 'database'
        #connection: @database_connection
        # настройки для 'filesystem'
        #path: %smart_core_cms_data_dir%

liip_imagine:
    filter_sets:
        100_100:
            format: jpeg
            quality: 100
            filters:
                thumbnail: { size: [100, 100], mode: inset }
        200_200:
            format: jpeg
            quality: 100
            filters:
                thumbnail: { size: [200, 200], mode: inset }
        300_300:
            format: jpeg
            quality: 100
            filters:
                thumbnail: { size: [300, 300], mode: inset }

doctrine_cache:
    providers:
        smart_texter:
            namespace: "smart_texter_%secret%"
            type: file_system # memcache
            file_system:
                directory: "%kernel.cache_dir%/smart_texter"
        cms:
            namespace: "cms_%secret%"
            type: file_system
            file_system:
                directory: "%kernel.cache_dir%/smart_core_cms"
        smart_blog: # @todo убрать
            namespace: "smart_blog_%secret%"
            type: file_system
            file_system:
                directory: "%kernel.cache_dir%/smart_blog"

fm_elfinder:
    instances:
        default:
            locale: %locale%    # defaults to current request locale
            editor: tinymce     # other choices are ckeditor, tinymce or simple
            tinymce_popup_path: "asset[bundles/stfalcontinymce/vendor/tiny_mce/tiny_mce_popup.js]"
            fullscreen: true    # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false    # defaults to false
                bind:
                    mkfile.pre:
                        - Plugin.Normalizer.cmdPreprocess
                        - Plugin.Sanitizer.cmdPreprocess
                    upload.presave:
                        - Plugin.Normalizer.onUpLoadPreSave
                        - Plugin.Sanitizer.onUpLoadPreSave
                plugin:
                    Normalizer:
                        enable: true
                        nfc: true
                        nfkc: true
                    Sanitizer:
                        enable: true
                        targets: ['\\','/',':','*','?','"','<','>','|',' ']
                        replace: '_'
                roots:          # at least one root must be defined
                    images:
                        driver: LocalFileSystem
                        path: images
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 50M
        tinymce4:
            locale: %locale%    # defaults to current request locale
            editor: tinymce4    # other choices are ckeditor, tinymce or simple
            tinymce_popup_path: "asset[bundles/stfalcontinymce/vendor/tiny_mce/tiny_mce_popup.js]"
            fullscreen: true    # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false    # defaults to false
                bind:
                    mkfile.pre:
                        - Plugin.Normalizer.cmdPreprocess
                        - Plugin.Sanitizer.cmdPreprocess
                    upload.presave:
                        - Plugin.Normalizer.onUpLoadPreSave
                        - Plugin.Sanitizer.onUpLoadPreSave
                plugin:
                    Normalizer:
                        enable: true
                        nfc: true
                        nfkc: true
                    Sanitizer:
                        enable: true
                        targets: ['\\','/',':','*','?','"','<','>','|',' ']
                        replace: '_'
                roots:          # at least one root must be defined
                    images:
                        driver: LocalFileSystem
                        path: images
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M
                    uploads:
                        driver: LocalFileSystem
                        path: uploads
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 50M

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: SmartCore\Bundle\CMSBundle\Entity\User
    registration:
        confirmation:
            enabled: true
            from_email:
                address: %registration_email_confirmation%
                sender_name: Email confirmation
    resetting:
        email:
            from_email:
                address: %email_resetting%
                sender_name: Password resetting

genemu_form:
    image: ~
    file:
        swf: /assets/uploadify/uploadify.swf
        folder: /uploads

knp_menu:
    twig:
        template: CMSBundle:Menu:knp_menu.html.twig

knp_disqus:
    api_key: %knp_disqus.api_key%

liip_theme:
    path_patterns:
        #app_resource:
            #- %%site_dir%%/modules/%%bundle_name%%/%%module_theme%%/%%template%%
        bundle_resource_dir:
            - %%site_dir%%/modules/%%bundle_name%%/%%module_theme%%/%%template%%
        bundle_resource:
            - %%site_dir%%/modules/%%bundle_name%%/%%module_theme%%/%%template%%

mopa_bootstrap:
    form:
        templating: false
        show_legend: false # default is true
        checkbox_label: label
        error_type: block # or inline which is default
        date_wrapper_class:
            year: col-xs-1
            month: col-xs-1
            day: col-xs-1
        horizontal: true
        horizontal_label_class: ''
        horizontal_label_offset_class: ''
        horizontal_input_wrapper_class: controls
        render_optional_text: false
        render_required_asterisk: true

security:
    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_USER ]
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_GUEST ]
        ROLE_ROOT:        [ ROLE_USER, ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_GUEST ]
        #ROLE_USER:        [ROLE_COMMENTER]

smart_rich_editor:
    include_jquery: false
    tinymce_jquery: true
    textarea_class: 'wysiwyg'
    language: %locale%
    theme:
        advanced:
            file_browser_callback : 'elFinderBrowser'
            theme: "advanced"
            plugins: "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist"
            theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect"
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor"
            theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen"
            theme_advanced_toolbar_location: "top"
            theme_advanced_toolbar_align: "left"
            theme_advanced_statusbar_location: "bottom"
            theme_advanced_resizing: true
            theme_advanced_resizing_use_cookie: true
            theme_advanced_resize_horizontal: false
            force_br_newlines : false
            forced_root_block : ""
            convert_urls : false
            relative_urls: false
            width: "100%"
            height: 380
            content_css: "asset[bundles/felib/tinymce/content.css]"
        simple:
            theme: "simple"
            force_br_newlines : false
            forced_root_block : ""
            convert_urls : false
            relative_urls: false
            width: "100%"
            height: 180
            content_css: "asset[bundles/felib/tinymce/content.css]"

stfalcon_tinymce:
    use_callback_tinymce_init: true
    theme:
        advanced:
            file_browser_callback: 'elFinderBrowser'
            plugins:
                - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                - "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "insertdatetime media nonbreaking save table contextmenu directionality"
                - "emoticons template paste textcolor"
            toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | preview media | forecolor backcolor emoticons"
            image_advtab: true
            force_br_newlines : false
            forced_root_block : ""
            convert_urls : false
            relative_urls: false
            height: 380
            content_css: "asset[bundles/felib/tinymce/content.css]"

tagcache:
    driver:        %tagcache_driver% # Memcache, Memcached, File, Sqlite, Apc, Nullcache
    #debug:         %kernel.debug%
    namespace:     %secret%
    options:
        cache_dir: "%kernel.cache_dir%/smart_core_tagcache"
        hashkey:   true
        servers:
            - 'localhost:11211:10'
