
cms_admin_module_routes:
    resource: .
    type: module_admin

cms_admin:
    resource: 'routing_admin.yml'
    prefix: /admin/

cms_api:
    resource: 'routing_api.yml'
    prefix: /api/

cms_node_mapper:
    path: /{slug}
    methods: GET
    defaults:
        _controller: CMSBundle:Engine:run
        slug: ''
    requirements:
        slug: '.+'

cms_node_postprocessor:
    path: /{slug}
    methods: POST
    defaults:
        _controller: CMSBundle:Engine:post
        slug: ''
    requirements:
        slug: '.+'

# Эти маршруты нужны для генерации ссылок к модулям с учетом пути, куда они подключены.
cms_modules:
    resource: .
    type: installed_modules
