
cms_admin_index:
    path: /
    defaults:
        _controller: CMSBundle:Admin:index

# Security
#cms_admin_login:
#    path: /login
#    defaults:
#        _controller: FrameworkBundle:Template:template
#        template: 'CMSBundle:User:login.html.twig'

cms_admin_logout:
    path: /logout
    defaults:
        _controller: FOSUserBundle:Security:logout

# Structure
cms_admin_structure:
    path: /structure/
    defaults:
        _controller: CMSBundle:AdminStructure:structure

# Region
cms_admin_structure_region:
    path: /structure/region/
    defaults:
        _controller: CMSBundle:AdminStructure:regionIndex

cms_admin_structure_region_edit:
    path: /structure/region/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:regionEdit
    requirements:
        id: \d+

# Folder
cms_admin_structure_folder_create:
    path: /structure/folder/create/
    defaults:
        _controller: CMSBundle:AdminStructure:folderCreate
        parent: 1

cms_admin_structure_folder_create_in_folder:
    path: /structure/folder/create/{parent}/
    defaults:
        _controller: CMSBundle:AdminStructure:folderCreate
    requirements:
        parent: \d+

cms_admin_structure_folder:
    path: /structure/folder/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:folderEdit
    requirements:
        id: \d+

# Node
cms_admin_structure_node_create:
    path: /structure/node/create/
    defaults:
        _controller: CMSBundle:AdminStructure:nodeCreate

cms_admin_structure_node_create_in_folder:
    path: /structure/node/create/{folder_pid}/
    defaults:
        _controller: CMSBundle:AdminStructure:nodeCreate

#cms_admin_structure_node_all:
#    path: /structure/node/
#    defaults:
#        _controller: CMSBundle:AdminStructure:node

cms_admin_structure_node_properties:
    path: /structure/node/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:nodeEdit
    requirements:
        id: \d+

cms_admin_node:
    path: /node/{id}/
    defaults:
        _controller: CMSBundle:AdminStructure:node
    requirements:
        id: \d+

cms_admin_node_w_slug:
    path: /node/{id}/{slug}
    defaults:
        _controller: CMSBundle:AdminStructure:node
    requirements:
        id: \d+
        slug: ".+"

# Appearance
cms_admin_appearance:
    path: /appearance/
    defaults:
        _controller: CMSBundle:AdminAppearance:index

cms_admin_appearance_template:
    path: /appearance/{name}.twig/
    defaults:
        _controller: CMSBundle:AdminAppearance:templateEdit

cms_admin_appearance_template_history:
    path: /appearance/{name}.twig/history/
    defaults:
        _controller: CMSBundle:AdminAppearance:templateHistory

cms_admin_appearance_style_history:
    path: /appearance/{name}/history/
    defaults:
        _controller: CMSBundle:AdminAppearance:styleHistory

cms_admin_appearance_history_code:
    path: /appearance/history/{id}/
    defaults:
        _controller: CMSBundle:AdminAppearance:historyCode

cms_admin_appearance_history_rollback:
    path: /appearance/history/rollback/{id}/
    defaults:
        _controller: CMSBundle:AdminAppearance:historyRollback

cms_admin_appearance_style:
    path: /appearance/{name}/
    defaults:
        _controller: CMSBundle:AdminAppearance:styleEdit

cms_admin_files:
    path: /files/
    defaults:
        _controller: CMSBundle:Admin:elfinder

# Modules
cms_admin_module:
    path: /module/
    defaults:
        _controller: CMSBundle:Admin:module

cms_admin_module_install_updatedb:
    path: /module/install/updatedb
    methods: 'POST'
    defaults:
        _controller: CMSBundle:Admin:moduleInstallUpdateDb

cms_admin_module_install:
    path: /module/install/{filename}
    defaults:
        _controller: CMSBundle:Admin:moduleInstall
        filename: ""

# Users
cms_admin_user:
    path: /user/
    defaults:
        _controller: CMSBundle:AdminUser:index

cms_admin_user_create:
    path: /user/create/
    defaults:
        _controller: CMSBundle:AdminUser:create

cms_admin_user_roles:
    path: /user/roles/
    defaults:
        _controller: CMSBundle:AdminUser:roles

cms_admin_user_role_edit:
    path: /user/role/{id}/
    defaults:
        _controller: CMSBundle:AdminUser:roleEdit

cms_admin_user_edit:
    path: /user/{id}/
    defaults:
        _controller: CMSBundle:AdminUser:edit

# Configuration
cms_admin_config:
    path: /config/
    defaults:
        _controller: CMSBundle:AdminConfig:index

cms_admin_config_edit_setting:
    path: /config/setting_{id}/
    defaults:
        _controller: CMSBundle:AdminConfig:editSetting
    requirements:
        id: \d+

cms_admin_config_media:
    path: /config/media/
    defaults:
        _controller: CMSBundle:AdminMediaLibrary:index

cms_admin_config_media_create_storage:
    path: /config/media/storage_create/
    defaults:
        _controller: CMSBundle:AdminMediaLibrary:createStorage

cms_admin_config_media_edit_storage:
    path: /config/media/storage_{id}/
    defaults:
        _controller: CMSBundle:AdminMediaLibrary:editStorage
    requirements:
        id: \d+

cms_admin_config_media_create_collection:
    path: /config/media/collection_create/
    defaults:
        _controller: CMSBundle:AdminMediaLibrary:createCollection

cms_admin_config_media_edit_collection:
    path: /config/media/collection_{id}/
    defaults:
        _controller: CMSBundle:AdminMediaLibrary:editCollection
    requirements:
        id: \d+

# @todo
cms_admin_reports:
    path: /reports/
    defaults:
        _controller: CMSBundle:Admin:notFound

cms_admin_help:
    path: /help/
    defaults:
        _controller: CMSBundle:Admin:notFound


# ... other
cms_admin:
    path: /{slug}
    defaults:
        _controller: CMSBundle:Admin:notFound
        slug: ""
    requirements:
        slug: ".+"
