imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@CMSBundle/Resources/config/config.yml" }

framework:
    annotations:
        debug:       %kernel.debug%
    csrf_protection:
        enabled:     true
    default_locale:  %locale%
    esi:             
        enabled:     false
    form:            true
    validation:      { enable_annotations: true }
    profiler:
        enabled:     false
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    secret:          %secret%
    session:
        handler_id:  %session_handler%
    templating:      { engines: ['twig', 'php'] } #assets_version: SomeVersionScheme
    translator:      { fallback: en }

avalanche_imagine:
    filters:
        100-100:
            type:    thumbnail
            options: { size: [100, 100], mode: inset, quality: 100, format: jpeg }
        200-200:
            type:    thumbnail
            options: { size: [200, 200], mode: inset, quality: 100, format: jpeg }
        300-300:
            type:    thumbnail
            options: { size: [300, 300], mode: inset, quality: 100, format: jpeg }

fm_elfinder:
    locale: %locale% # defaults to current request locale
    editor: tinymce # other choices are ckeditor, tinymce or simple
    tinymce_popup_path: "asset[bundles/stfalcontinymce/vendor/tiny_mce/tiny_mce_popup.js]"
    showhidden: false # defaults to false
    fullscreen: true # defaults true, applies to simple and ckeditor editors
    include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
    compression: false # enable if you configured the uglifycss and uglifyjs2 assetic filters and want compression
    connector:
        debug: true # defaults to false
        roots:       # at least one root must be defined
            uploads:
                driver: LocalFileSystem
                path: uploads
                upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                upload_deny: ['all']
                upload_max_size: 2M

genemu_form:
    image: ~
    file:
        swf: /assets/uploadify/uploadify.swf

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: false
    autoescape:       false
    form:
        resources:
            - 'UnicatBundle:Form:fields.html.twig' # @todo убрать в бандл юниката

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [FMElfinderBundle]
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
                logging:  %kernel.debug%
                unix_socket: /var/run/mysqld/mysqld.sock
                mapping_types:
                    enum: string                
            #db1:
                #driver:   %database_driver_db1%
                #port:     %database_port_db1%
                #dbname:   %database_name_db1%
                #user:     %database_user_db1%
                #password: %database_password_db1%
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:
        type:  file
        path:  %kernel.root_dir%/../var/mailspool

stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    textarea_class: 'wysiwyg'
    language: %locale%
    theme:
        advanced:
            file_browser_callback : 'elFinderBrowser'
            theme: "advanced"
            plugins: "autolink,lists,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,advlist"
            theme_advanced_buttons1: "save,newdocument,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect"
            theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,help,code,|,insertdate,inserttime,preview,|,forecolor,backcolor"
            theme_advanced_buttons3: "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,emotions,iespell,media,advhr,|,print,|,ltr,rtl,|,fullscreen"
            theme_advanced_toolbar_location: "top"
            theme_advanced_toolbar_align: "left"
            theme_advanced_statusbar_location: "bottom"
            theme_advanced_resizing: true
            theme_advanced_resizing_use_cookie: true
            theme_advanced_resize_horizontal: false
            force_br_newlines : false
            forced_root_block : ""
            convert_urls : false
            relative_urls: false
            width: "100%"
            height: 380
            content_css: "/assets/tinymce/css/content.css" # @todo настройка в формате "asset[path/to/style.css]"
        simple:
            theme: "simple"
            force_br_newlines : false
            forced_root_block : ""
            convert_urls : false
            relative_urls: false
            width: "100%"
            height: 180
            content_css: "/assets/tinymce/css/content.css" # @todo настройка в формате "asset[path/to/style.css]"

knp_disqus:
    api_key: %knp_disqus.api_key%

liip_doctrine_cache:
    namespaces:
        smart_texter:
            namespace: "smart_texter_%secret%"
            type: file_system # memcache
            directory: "%kernel.cache_dir%/smart_texter"
        cms:
            namespace: "cms_%secret%"
            type: file_system
            directory: "%kernel.cache_dir%/smart_core_cms"
        smart_blog: # @todo убрать
            namespace: "smart_blog_%secret%"
            type: file_system
            directory: "%kernel.cache_dir%/smart_blog"

liip_theme:
    themes: ['web', 'tablet', 'phone']
    active_theme: ~
    autodetect_theme: false
    load_controllers: false

smart_sitemap:
    base_url: %base_url%
    ignores:
        - 'http:'
        - 'https:'
        - 'javascript:'
        - 'mailto:'
        - 'skype:'
        - /user/
        - /admin/
        - /api/

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: SmartCore\Bundle\FOSUserBundle\Entity\User
    registration:
        confirmation:    
            enabled: true
            from_email:
                address: %registration_email_confirmation%
                sender_name: Email confirmation
    resetting:
        email:
            from_email:
                address: %email_resetting%
                sender_name: Password resetting
tagcache:
    driver:        %tagcache_driver% # Memcache, Memcached, File, Sqlite, Apc, Nullcache
    #debug:         %kernel.debug%
    namespace:     %secret%
    options:
        cache_dir: "%kernel.cache_dir%/smart_core_tagcache"
        hashkey:   true
        servers:
            - 'localhost:11211:10'
