imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: '@CMSBundle/Resources/config/config.yml' }

framework:
    annotations:
        debug:       %kernel.debug%
    csrf_protection:
        enabled:     true
    default_locale:  %locale%
    esi:             
        enabled:     false
    form:            true
    validation:      { enable_annotations: true }
    profiler:
        enabled:     false
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    secret:          %secret%
    session:
        handler_id:  %session_handler%
        save_path:   "%kernel.root_dir%/../var/sessions"
    templating:      { engines: ['twig', 'php'] } #assets_version: SomeVersionScheme
    translator:      { fallback: en }

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: false
    autoescape:       false

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['FMElfinderBundle']
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

dizda_cloud_backup:
    output_file_prefix: smart_core_cms
    cloud_storages:
        dropbox:
            user:        %dizda_cloud_dropbox_user%
            password:    %dizda_cloud_dropbox_password%
            remote_path: %dizda_cloud_dropbox_remote_path%
    databases:
        mysql:
            all_databases: false        # Only required when no database is set
            database: %database_name%   # Required if all_databases is false

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                charset:  UTF8
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                unix_socket: %database_socket%
                logging:  %kernel.debug%
                mapping_types:
                    enum: string                
            #db2:
                #driver:   %database2_driver%
                #port:     %database2_port%
                #dbname:   %database2_name%
                #user:     %database2_user%
                #password: %database2_password%
                #unix_socket: %database2_socket%
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:
        type:  file
        path:  %kernel.root_dir%/../var/mailspool

#liip_theme:
#    themes: ['web', 'tablet', 'phone']
#    active_theme: ~
#    autodetect_theme: false
#    load_controllers: false

accelerator_cache:
    host: %base_url%
    web_dir: %kernel.root_dir%/../web
    mode: curl

smart_sitemap:
    base_url: %base_url%
    ignores:
        - 'http:'
        - 'https:'
        - 'javascript:'
        - 'mailto:'
        - 'skype:'
        - /user/
        - /admin/
        - /api/

#sp_bower:
#    bundles:
        #CMSBundle: ~
