imports:
    - { resource: config.yml }
    - { resource: '@SiteBundle/Resources/config/config.yml', ignore_errors: true }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler:
        enabled: true
        only_exceptions: false

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info

#assetic:
#    use_controller: true

#jms_debugging:
#    auto_help: true
    
web_profiler_extra:
    routing:
        enabled: true
        display_in_wdt: false
    container:
        enabled: true
        display_in_wdt: false
    assetic:
        enabled: true
        display_in_wdt: false
    twig:
        enabled: true
        display_in_wdt: false

#services:
#    data_collector.config:
#        class: Symfony\Component\HttpKernel\DataCollector\ConfigDataCollector
#        tags:
#           - {name: 'data_collector', priority: '0'}
