security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_USER ]
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false

#        login:
#            pattern:  ^/user/login$
#            security: false
         #sf2gen:
            #pattern:    /_sf2gencdt/.*
            #security:  false
#         admin_login:
#            pattern: ^/admin
#            anonymous:  ~
#            form_login:
#                check_path:  /admin/user/login_check
#                login_path:  /admin/user/
#                default_target_path:  /admin/
#            logout:
#                path:   /admin/user/logout
         main:
            pattern: ^/
            form_login:
                csrf_provider: form.csrf_provider
                check_path:  /user/login_check
                login_path:  /user/
                default_target_path:  /user/
            logout:
                path:   /user/logout
            remember_me:
                key:    "%secret%"
                name:   SMART_CORE_REMEMBER_ME
                lifetime: 36000
                path:     /
                domain:   ~
            anonymous: ~
            #http_basic:
                #realm: "Secured Demo Area"
    access_control:
#        - { path: ^/admin/user, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/efconnect, role: ROLE_ADMIN }
        - { path: ^/elfinder, role: ROLE_ADMIN }
        #- { path: ^/user, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
