bootstrap:
    version: 2.3.2
    deps: jquery
    css: { css/bootstrap.min.css, css/bootstrap-responsive.min.css }
    js: js/bootstrap.min.js

highlightjs:
    version: 8.0
    css:
        - styles/github.min.css
        - styles/vs.min.css
    js:
        - highlight.min.js
        - languages/php.min.js
    profile:
        yandex:
            js: http://yandex.st/highlightjs/

jquery:
    version: 1.9.1
    proirity: 1000
    js: jquery.min.js
    profile:
        google:
            js: //ajax.googleapis.com/ajax/libs/jquery/
        yandex:
            js: http://yandex.st/jquery/

jquery-cookie:
    deps: jquery
    version: 1.3.1
    js: jquery.cookie.js

less:
    version: 1.7.0
    js: less.min.js

modernizr:
    version: 2.7.1
    js: modernizr.min.js
    profile:
        yandex:
            js: http://yandex.st/modernizr/
