SmartCore\Module\Unicat\Entity\UnicatConfiguration:
    properties:
        name:
            - Regex:
                pattern: '/^[a-z]+$/'
                htmlPattern: '^[a-z]+$'
                message: Имя может состоять только из латинских букв в нижнем регистре.
        title:
            - NotBlank: ~
