parameters:
    # путь для хранения данных (структура сайтов, данные модулей и т.д.)
    smart_core_engine_data_dir: %kernel.root_dir%/usr/site

# Пример конфигурирования
smart_core_engine:
    # database (db), filesystem (fs)
    storage: database
        # настройки для 'database'
        connection: @database_connection
        # настройки для 'filesystem'
        path: %smart_core_engine_data_dir%
