smart_blog_admin_article:
    path: /
    defaults: { _controller: BlogModule:Admin/Article:index }

smart_blog_admin_article_edit:
    path: /article/{id}/
    defaults: { _controller: BlogModule:Admin/Article:edit }
    requirements:
        id: \d+

smart_blog_admin_article_create:
    path: /article/create/
    defaults: { _controller: BlogModule:Admin/Article:create }

smart_blog_admin_category:
    path: /category/
    defaults: { _controller: BlogModule:Admin/Category:index }

smart_blog_admin_category_edit:
    path: /category/{id}/
    defaults: { _controller: BlogModule:Admin/Category:edit }
    requirements:
        id: \d+

smart_blog_admin_category_create:
    path: /category/create/
    defaults: { _controller: BlogModule:Admin/Category:create }

smart_blog_admin_tag:
    path: /tag/
    defaults: { _controller: BlogModule:Admin/Tag:index }

smart_blog_admin_tag_edit:
    path: /tag/{id}/
    defaults: { _controller: BlogModule:Admin/Tag:edit }
    requirements:
        id: \d+
