parameters:
    smart_blog.items_per_page: 10
    smart_blog.model.article.class: SmartCore\Module\Blog\Entity\Article
    smart_blog.model.tag.class: SmartCore\Module\Blog\Entity\Tag
    smart_blog.model.category.class: SmartCore\Module\Blog\Entity\Category

services:
    smart_blog.article:
        class: SmartCore\Module\Blog\Service\ArticleService
        arguments:
            - @doctrine.orm.default_entity_manager
            - @smart_blog.article.repository
            - @smart_blog.cache
            - @event_dispatcher
            - %smart_blog.items_per_page%

    smart_blog.tag:
        class: SmartCore\Module\Blog\Service\TagService
        arguments:
            - @doctrine.orm.default_entity_manager
            - @smart_blog.article.repository
            - @smart_blog.cache
            - @smart_blog.tag.repository
            - @event_dispatcher
            - @router
            - %smart_blog.items_per_page%

    smart_blog.category:
        class: SmartCore\Module\Blog\Service\CategoryService
        arguments:
            - @doctrine.orm.default_entity_manager
            - @smart_blog.category.repository
            - @smart_blog.cache
            - @event_dispatcher

    smart_blog.cache: # @todo настройку через конфиг.
        alias: doctrine_cache.providers.smart_blog

    smart_blog.listener.cache.invalidate:
        class: SmartCore\Module\Blog\EventListener\CacheInvalidateListener
        arguments: [@smart_blog.cache]
        tags:
            - { name: kernel.event_subscriber }

    smart_blog.article.create.form.type:
        class: SmartCore\Module\Blog\Form\Type\ArticleCreateFormType
        arguments: [%smart_blog.model.article.class%]

    smart_blog.article.edit.form.type:
        class: SmartCore\Module\Blog\Form\Type\ArticleEditFormType
        arguments: [%smart_blog.model.article.class%]

    smart_blog.category.create.form.type:
        class: SmartCore\Module\Blog\Form\Type\CategoryCreateFormType
        arguments: [%smart_blog.model.category.class%]

    smart_blog.category.edit.form.type:
        class: SmartCore\Module\Blog\Form\Type\CategoryEditFormType
        arguments: [%smart_blog.model.category.class%]

    smart_blog.tag.create.form.type:
        class: SmartCore\Module\Blog\Form\Type\TagCreateFormType
        arguments: [%smart_blog.model.tag.class%]

    smart_blog.tag.edit.form.type:
        class: SmartCore\Module\Blog\Form\Type\TagEditFormType
        arguments: [%smart_blog.model.tag.class%]

    smart_blog.article.repository:
        class:           SmartCore\Module\Blog\Repository\ArticleRepository
        factory_service: doctrine
        factory_method:  getRepository
        arguments:       [%smart_blog.model.article.class%]

    smart_blog.tag.repository:
        class:           SmartCore\Module\Blog\Repository\TagRepository
        factory_service: doctrine
        factory_method:  getRepository
        arguments:       [%smart_blog.model.tag.class%]

    smart_blog.category.repository:
        class:           SmartCore\Module\Blog\Repository\CategoryRepository
        factory_service: doctrine
        factory_method:  getRepository
        arguments:       [%smart_blog.model.category.class%]

    # Listeners
    smart_blog.listener.article_author:
        class: SmartCore\Module\Blog\EventListener\ArticleAuthorListener
        arguments: [@security.context, @logger]
        tags:
            - { name: kernel.event_subscriber }
